In [1]:
import pandas as pd
df= pd.read_json("One_Piece_json[1].json")
df

,Unnamed: 0,rank,trend,season,episode,name,start,total_votes,average_rating
0,0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
...,...,...,...,...,...,...,...,...,...
953,953,"41,448",26,1,954,Its Name is Enma! Oden's Meito!,2020,302,7.7
954,954,"35,342",44,1,955,&quot;A New Alliance?! Kaido's Army Gathers&quot;,2020,407,7.4
955,955,"33,715",75,1,956,Ticking Down to the Great Battle! The Straw Ha...,2020,353,8.2
956,956,"2,940",964,1,957,Big News! The Warlords Attack Incident,2021,"2,862",9.1
957,957,"14,751",-,1,958,&quot;The Legendary Battle! Garp and Roger&quot;,2021,746,9.4

In [5]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in c:\users\admin\anaconda3\lib\site-packages (2.2.9)

In [6]:
import mysql.connector
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 No connection could be made because the target machine actively refused it)